dist: xenial
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - lts/*
  - node
install: npm ci
script:
  - npm run build:server:protos
  - npm run build:client
  - npm test
jobs:
  include:
    - stage: coverage
      node_js: lts/*
      install: npm ci
      script:
        - npm run build:server:protos
        - npm run build:client
        - jest --coverage --coverageReporters=text-lcov | coveralls
    - stage: deploy
      if: branch = master && commit_message !~ /no-deploy/
      node_js: lts/*
      install: npm ci
      script: skip
      deploy:
        provider: npm
        email: litichevskiydv@gmail.com
        api_key:
          secure: uOp4rTtMkPaX3LV6b7tzg1BFiOQGs58FHCmA38EbKYL7pQyZ07WngaJLaQBsje/OPR32IMHJEkIDvtO3RhUFRHh7x6gpWu++HPSwgbR2OsYNoYhfCIJarjiHHKWIYEL8VoPsMtcp2UrNi8sw1O3vVSnbuJzjTdM2tRvAnKoWeIO8vxrF5K+ZlLzcwDDpUm6MDCVkyhW8pHr4ZHUpN/1JB7d5lACUQiM6FVeuTzwbtq5zVzYNDLJsBsOz6jL6zV+oammdFmmIAsMNVrSPW9PZInCzMx68yTetMnMRyPLgdv6qB8ZnR0lzVBD2K4oWJhLX2BviovDUr6IuQhwOULQDJqV67ntfCKXfQInDhuuyVt3Q/ta2zVAd12Yk18eXlAQ102125y9pXTevDSLFep9cgN8TAuAt2O3LStzyZv+yN1WzeTWCvkc/F634J2Iz6TRdpcJ84Pnlvz5Pup2uB+69SS0EGJRaWwJidoxb6rXU5/u9mZOgoEU7abgm9ydso15BjNEj8JTYTKd3bEv0FJFXRBkEVas0/qsdV0d93f3iSesQmpUcRqjIiWMRtRvq5Unp/IuymTfE4qJyW7c9ojTNZfdYLEVh90FbkpSorpIfIysfDPkiANu0tbecySoRuSHySE8L0K7ZpxZsOlLt0tjMT7h8baNKfpD/nNrMi+Dp9CU=
